notifications:
  email: false
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_script:
  - npm install -g jest-cli
  - npm install -g https://github.com/ebidel/lighthouse-ci
script:
  - npm run build
  - jest test --ci --colors

before_deploy:
  - openssl aes-256-cbc -K $encrypted_e01d503bebb6_key -iv $encrypted_e01d503bebb6_iv -in .travis/deploy_rsa.enc -out /tmp/deploy_rsa -d
after_sucess:
  - ./.travis/deploy-pr.sh
  - lighthouse-ci --score=85 staging.streamwave.be
